// <auto-generated />
using FacilityProductionManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FacilityProductionManagement.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20250118130545_UpdateRelationships")]
    partial class UpdateRelationships
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FacilityProductionManagement.Model.EquipmentContract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EquipmentTypeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FacilityCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentTypeCode");

                    b.HasIndex("FacilityCode");

                    b.ToTable("EquipmentContract", "dbo");
                });

            modelBuilder.Entity("FacilityProductionManagement.Model.EquipmentType", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Area")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Code");

                    b.ToTable("EquipmentType", "dbo");
                });

            modelBuilder.Entity("FacilityProductionManagement.Model.Facility", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("StandardArea")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Code");

                    b.ToTable("Facility", "dbo");
                });

            modelBuilder.Entity("FacilityProductionManagement.Model.EquipmentContract", b =>
                {
                    b.HasOne("FacilityProductionManagement.Model.EquipmentType", "EquipmentType")
                        .WithMany("EquipmentContracts")
                        .HasForeignKey("EquipmentTypeCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FacilityProductionManagement.Model.Facility", "Facility")
                        .WithMany("EquipmentContracts")
                        .HasForeignKey("FacilityCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EquipmentType");

                    b.Navigation("Facility");
                });

            modelBuilder.Entity("FacilityProductionManagement.Model.EquipmentType", b =>
                {
                    b.Navigation("EquipmentContracts");
                });

            modelBuilder.Entity("FacilityProductionManagement.Model.Facility", b =>
                {
                    b.Navigation("EquipmentContracts");
                });
#pragma warning restore 612, 618
        }
    }
}
